# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" "sr_mod"];
  boot.initrd.kernelModules = ["virtio_gpu"];
  boot.kernelModules = [];
  boot.extraModulePackages = [];
  boot.kernelParams = [
    "console=tty"
    "cgroup_disable=hugetlb"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "ext4";
    options = ["noatime"];
  };

  swapDevices = [
    {device = "/dev/disk/by-label/NIXSWAP";}
  ];

  networking.useNetworkd = true;
}
