# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ "virtio_gpu" ];
  boot.kernelParams = [ "console=tty" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  networking.useNetworkd = true;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-label/NIXSWAP"; }
  ];

  fileSystems."/mnt/storagebox" = {
    device = "//u410238.your-storagebox.de/backup";
    fsType = "cifs";
    options = [
      "_netdev"
      "credentials=/root/.config/storagebox-secrets"
      "uid=1000"
      "gid=1000"
      "echo_interval=30"
      "vers=3.0"
    ];
  };

  #fileSystems."/mnt/media" = {
    #device = "/mnt/storagebox/media";
    #fsType = "fuse./etc/profiles/per-user/manolis/bin/gocryptfs";
    #noCheck = true;
    #options = [
      #"allow_other"
      #"nofail"
      #"passfile=/root/.config/media-gocryptfs"
    #];
    #depends = [
      #"/mnt/storagebox"
    #];
  #};
}
